@startuml "Context Diagram"

title "OC-Medico Interno - Diagrama de contexto do sistema"

!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Context.puml

LAYOUT_WITH_LEGEND()
LAYOUT_LEFT_RIGHT()

skinparam backgroundcolor transparent

/'Actors'/
Person(ActorPhysician, "Médico", "É o ator responsável por realizar a interação com o sistema")

/'Internal Systems'/
System(SystemOCInternalPhysician, "Sistema OC-Médico Interno", "Responsável pelas funcionalidades: listagem de consultas, visualização de laudos, visualização de protocolos preferenciais.")

/'External Systems'/
System_Ext(SystemMyPhysicianApi, "API Meu Médico", "Responsável por fornecer conexão direta com o sistema Meu Médico.")
System_Ext(SystemTasyApi, "API Tasy", "Responsável por fornecer conexão direta com o sistema Tasy.")
System_Ext(SystemAWSCognito, "AWS Cognito", "Responsável por gerenciar todo a autenticação do usuário (Cadastro, Login, MFA, Recuperação de conta).")
System_Ext(SystemAWSSecretManager, "AWS SecretManager", "Responsável por gerenciar variáveis de ambiente.")

/'Relations'/
Rel(ActorPhysician, SystemOCInternalPhysician, "Visualiza e interage com as funcionalidades do sistema")
Rel(SystemOCInternalPhysician, SystemAWSCognito, "Autentica o médico", "@aws-sdk/client-cognito-identity-provider")
Rel(SystemOCInternalPhysician, SystemAWSSecretManager, "Obtém variáveis de ambiente", "@aws-sdk/client-secrets-manager")
Rel(SystemOCInternalPhysician, SystemMyPhysicianApi, "Realiza SSO", "JSON/HTTPS")
Rel(SystemOCInternalPhysician, SystemTasyApi, "Obtém dados do Tasy", "JSON/HTTPS")

@enduml