@startuml "Context Diagram"

title "OC-Medico Interno - Diagrama de contexto do sistema"

!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Context.puml

LAYOUT_WITH_LEGEND()
LAYOUT_LEFT_RIGHT()

skinparam backgroundcolor transparent

/'Actors'/
Person(ActorInternalPhysician, "Médico Interno", "É o ator responsável por realizar a interação com o sistema")

/'Internal Systems'/
System(SystemOCInternalPhysician, "Sistema OC-Médico Interno", "<b>Funcionalidades</b>: listagem de pacientes e agenda, prontuário, treinamento (Grano), laudos, protocolos preferenciais, telemedicina.")

/'External Systems'/
System_Ext(SystemTasyApi, "API Tasy", "Responsável por fornecer conexão direta com o sistema Tasy.")

/'API-Core Systems'/
System_Ext(SystemApiCore, "API Core", "Responsável por fornecer conexão direta com a api-core.")
System_Ext(SystemMevo, "Mevo", "Responsável pela geração de receitas médicas digitais.")
System_Ext(SystemSalesForce, "API SalesForce", "Responsável pela abertura de caso e criação de usuário SalesForce.")
System_Ext(SystemGrano, "Grano", "Responsável pelo treinamento das ferramentas internas da Oncoclinicas.")
System_Ext(SystemNetshow, "API Netshow", "Responsável pelo acesso ao Instituto Oncoclínicas de Ensino, Pesquisa e Educação Médica Continuada.")

/'AWS Systems'/
System_Ext(SystemAWSCognito, "AWS Cognito", "Responsável por gerenciar a autenticação do usuário (Login, MFA).")

/'Relations'/
Rel(ActorInternalPhysician, SystemOCInternalPhysician, "Visualiza e interage com as funcionalidades do sistema")
Rel(SystemOCInternalPhysician, SystemAWSCognito, "Autentica o médico", "JSON/HTTPS")
Rel(SystemOCInternalPhysician, SystemTasyApi, "Obtém dados do sistema de gestão clinico", "JSON/HTTPS")

/'API-Core Integrations'/
Rel(SystemOCInternalPhysician, SystemApiCore, "Gestão de dados do CMS e integrações", "JSON/HTTPS")
Rel(SystemApiCore, SystemTasyApi, "Obtém laudos dos pacientes", "JSON/HTTPS")
Rel(SystemApiCore, SystemMevo, "Emite receita médica digital", "JSON/HTTPS")
Rel(SystemApiCore, SystemSalesForce, "Criação de caso e usuário no SalesForce", "JSON/HTTPS")
Rel(SystemApiCore, SystemGrano, "Gera URL de acesso Grano", "JSON/HTTPS")
Rel(SystemApiCore, SystemNetshow, "Gera URL de acesso oc-academia", "JSON/HTTPS")

@enduml