@startuml "Container Diagram"

title "OC-OCPM - Diagrama de container do sistema"

!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Component.puml

LAYOUT_WITH_LEGEND()

skinparam backgroundcolor transparent

/'Actors'/
Person(ActorOCPMUser, "Usuário OCPM", "É o ator responsável por realizar a interação com o sistema")

/'Internal Systems'/
Container_Boundary(SystemOCOCPM, "Sistema OC-OCPM") {
  Container(ContainerWebApp, "Aplicação Web (oc-frontend-ocpm)", "Container: NextJS/React", "Provê aos usuários acesso as funcionalidades a partir do cliente.")

  Rel(ActorOCPMUser, ContainerWebApp, "Acessa ocpm-laudos.com", "HTTPS")
}

/'External Systems'/
System_Ext(SystemTasyApi, "API Tasy", "Responsável por fornecer conexão direta com o sistema Tasy.")

/'API-Core Systems'/
System_Ext(SystemApiCore, "API Core", "Responsável por fornecer conexão direta com a api-core.")

/'AWS Systems'/
System_Ext(SystemAWSCognito, "AWS Cognito", "Responsável por gerenciar todo a autenticação do usuário (Cadastro, Login, MFA, Recuperação de conta).")


/'API-Core Integrations'/
Rel(SystemOCOCPM, SystemApiCore, "Gestão de dados do CMS e integrações", "JSON/HTTPS")
Rel(SystemApiCore, SystemTasyApi, "Obtém dados do Tasy", "JSON/HTTPS")
Rel(SystemApiCore, SystemAWSCognito, "Autentica o médico", "JSON/HTTPS")

@enduml
