@startuml "Container Diagram"

title "OC-Medico Externo - Diagrama de container do sistema"

!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Component.puml

LAYOUT_WITH_LEGEND()

skinparam backgroundcolor transparent

/'Actors'/
Person(ActorReferrerPhysician, "Médico Externo", "Médico externo que consegue acessar as funcionalidades do sistema.")
Person(ActorReferrerAssistant, "Assistente", "Assistente do médico externo.")

/'Internal Systems'/
Container_Boundary(SystemOCExternaPhysician, "Sistema OC-Médico Externo") {
  Container(ContainerWebApp, "Aplicação Web (oc-frontend-referrer)", "Container: NextJS/React", "Provê aos usuários acesso as funcionalidades a partir do cliente.")

  Rel(ActorReferrerPhysician, ContainerWebApp, "Acessa medico.grupooncoclinicas.com", "HTTPS")
  Rel(ActorReferrerAssistant, ContainerWebApp, "Acessa medico.grupooncoclinicas.com", "HTTPS")
}

/'External Systems'/
System_Ext(SystemTasyApi, "API Tasy", "Responsável por fornecer conexão direta com o sistema Tasy.")

/'API-Core Systems'/
System_Ext(SystemApiCore, "API Core", "Responsável por fornecer conexão direta com a api-core.")

/'AWS Systems'/
System_Ext(SystemAWSCognito, "AWS Cognito", "Responsável por gerenciar todo a autenticação do usuário (Cadastro, Login, MFA, Recuperação de conta).")
System_Ext(SystemAWSSecretManager, "AWS SecretManager", "Responsável por gerenciar variáveis de ambiente.")


/'API-Core Integrations'/
Rel(SystemOCExternaPhysician, SystemApiCore, "Gestão de dados do CMS e integrações", "JSON/HTTPS")
Rel(SystemApiCore, SystemTasyApi, "Obtém dados do Tasy", "JSON/HTTPS")
Rel(SystemApiCore, SystemAWSCognito, "Autentica o médico", "JSON/HTTPS")
Rel(SystemApiCore, SystemAWSSecretManager, "Obtém variáveis de ambiente", "JSON/HTTPS")

@enduml
