@startuml "Context Diagram"

title "OC-Patient - Diagrama de contexto do sistema"

!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Context.puml

LAYOUT_WITH_LEGEND()
LAYOUT_LEFT_RIGHT()

skinparam backgroundcolor transparent

Person(ActorPatient, "Paciente", "É o ator responsável por realizar a interação com o sistema ")

System(SystemOCPatient, "Sistema OC-Paciente", "Responsável por fornecer os seguintes principais serviços: agendamento de consultas, cadastrar uma acompanhante, autorizar acesso a prontuário e visualização dos resultados de exames.")

System(SystemRedis, "Redis", "Sistema de cacheamento Redis. Responsável por realizar o cacheamento de dados.")

System_Ext(SystemMyPhysicianApi, "API Meu Médico", "Responsável por fornecer conexão direta com o sistema Meu Médico.")

System_Ext(SystemCMSApi, "API Core", "Responsável por fornecer conexão direta com os dados do CMS da api-core.")

System_Ext(SystemTasyApi, "API Tasy", "Responsável por fornecer conexão direta com o sistema Tasy.")

System_Ext(SystemAWSCognito, "AWS Cognito", "Responsável por gerenciar todo a autenticação do usuário (Cadastro, Login, MFA, Recuperação de conta).")

System_Ext(SystemGoogleRecaptcha, "Google Recaptcha", "Responsável por validar token recaptcha.")


Rel(ActorPatient, SystemOCPatient, "Visualiza e interage com as funcionalidades do sistema")
Rel(SystemOCPatient, SystemRedis, "Cachea dados", "cache-manager-redis-store")
Rel(SystemOCPatient, SystemGoogleRecaptcha, "Valida token recaptcha", "@google-cloud/recaptcha-enterprise")
Rel(SystemOCPatient, SystemAWSCognito, "Autentica o paciente", "@aws-sdk/client-cognito-identity-provider")
Rel(SystemOCPatient, SystemMyPhysicianApi, "Obtém agendamentos do paciente", "Axios (HTTPs)")
Rel(SystemOCPatient, SystemTasyApi, "Obtém dados do Tasy", "Axios (HTTPs)")
Rel(SystemOCPatient, SystemCMSApi, "Gestão de acesso ao prontuário", "Axios (HTTPs)")

@enduml