@startuml "Context Diagram"

title "OC-Medico Externo - Diagrama de contexto do sistema"

!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Context.puml

LAYOUT_WITH_LEGEND()
LAYOUT_LEFT_RIGHT()

skinparam backgroundcolor transparent

/'Actors'/
Person(ActorReferrerPhysician, "Médico Externo", "Médico externo do grupo oncoclinicas que consegue acessar as funcionalidades do sistema.")
Person(ActorReferrerAssistant, "Assistente", "Indivíduo autorizado pelo médico para gerir seus dados.")

/'Internal Systems'/
System(SystemOCExternaPhysician, "Sistema OC-Médico Externo", "Responsável pelas funcionalidades: encaminhamento de pacientes, visualização de laudos, visualização de prontuários.")

/'External Systems'/
System_Ext(SystemTasyApi, "API Tasy", "Responsável por fornecer conexão direta com o sistema Tasy.")

/'API-Core Systems'/
System_Ext(SystemApiCore, "API Core", "Responsável por fornecer conexão direta com a api-core.")

/'AWS Systems'/
System_Ext(SystemAWSCognito, "AWS Cognito", "Responsável por gerenciar todo a autenticação do usuário (Cadastro, Login, MFA, Recuperação de conta).")


/'Relations'/
Rel(ActorReferrerPhysician, SystemOCExternaPhysician, "Visualiza e interage com as funcionalidades do sistema")
Rel(ActorReferrerAssistant, SystemOCExternaPhysician, "Visualiza e interage com as funcionalidades do sistema")

/'API-Core Integrations'/
Rel(SystemOCExternaPhysician, SystemApiCore, "Gestão de dados do CMS e integrações", "JSON/HTTPS")
Rel(SystemApiCore, SystemTasyApi, "Obtém dados do Tasy", "JSON/HTTPS")
Rel(SystemApiCore, SystemAWSCognito, "Autentica o médico", "JSON/HTTPS")

@enduml